### PR TITLE
Allow use of an existing *pgxpool.Pool instance

### PR DESCRIPTION
**Pull request by glimberg**
Adds a `WithConnectionPool` option fucntion, and modifies the `NewAdapter` function to test for the existence of a pool before creating a new one.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@pckhoi plz review

**Comment by pckhoi** [comment]
@glimberg can you please upgrade Go version. Looks like the tests are failing.

**Comment by glimberg** [comment]
Looks like the issue is in the CI config itself.  It's configured for go 1.18.  I'll go ahead and push a change to that in this PR

**Comment by hsluoyz** [comment]
@pckhoi

**Comment by glimberg** [comment]
@pckhoi Can we get a release with this change?

**Comment by pckhoi** [comment]
Sorry it showed for me then that this change is available in tag v3.1.0. I thought you saw that too.

**Pull request merged**
